### PR TITLE
DesignOps coach link

### PR DESCRIPTION
**Pull request by ttoh**
Added link to DesignOps Coach.

### CODE REVIEW

**Comment by ttoh** [comment]
Please merge.

**Comment by ttoh** [comment]
# MERGE!!!!!!!

**Comment by theinterned** [comment]
Chill I'm a maintainer. I have a lot of stuff to do.

**Comment by theinterned** [comment]
Hmm it looks like there is no styling on the link. Can  you please take a look at that?

**Comment by theinterned** [comment]
I am closing this PR as we have since moved to a different design for this page using http://catalog.style

**Pull request closed without merging**
